# coding: utf-8
"""
Certify
================

Module to automatically prove operator identities.

AUTHOR:

- Clemens Hofstadler (2020-02-16)

"""

#############################################################################
#  Copyright (C) 2020 Clemens Hofstadler (clemens.hofstadler@jku.at).       #
#                                                                           #
#  Distributed under the terms of the GNU General Public License (GPL)      #
#  either version 2, or (at your option) any later version                  #
#                                                                           #
#  http://www.gnu.org/licenses/                                             #
#############################################################################

import itertools
from time import time
from random import choice
import warnings

from sage.all import *

from .free_algebra import MyFreeAlgebra
from .nc_polynomial import NCPolynomial
from .nc_ideal import NCIdeal
from .auxiliary import *
from .normal_form import interreduce, reduced_form
from .quiver import Quiver

############################################################################
# Certify
############################################################################
def certify(assumptions,claims,quiver=None,maxiter=10,maxdeg=-1,order=None,verbose=1):
    r"""
    Certify that ``claims`` follow from ``assumptions``.

    Enumerates a (partial) Groebner basis of the ideal generated by
    ``assumptions`` and reduces the ``claims``. If a claim reduces to zero,
    the cofactor representation collected during the reduction proves it.

    INPUT:

    - ``assumptions`` -- a list of noncommutative polynomials

    - ``claims`` -- a noncommutative polynomial, or a list of them

    - ``quiver`` -- Quiver (default: ``None``); if given, the assumptions have
      to be uniformly compatible and the claims compatible with it

    - ``maxiter`` -- integer (default: 10); maximal number of iterations

    - ``maxdeg`` -- integer (default: -1); degree bound for the Groebner basis
      computation, ``-1`` meaning no bound

    - ``order`` -- the monomial order to use (default: ``None``)

    - ``verbose`` -- integer (default: 1); verbosity level

    OUTPUT: A cofactor representation of every claim, or ``False`` if not all
    ideal memberships could be verified. 
    
    EXAMPLES::

        sage: from operator_gb import *
        sage: F.<a,b> = FreeAlgebra(QQ,2)
        sage: proof = certify([a*b*a - a], a*b*a*b*a - a, verbose=0)
        sage: proof
        [(1,0,b*a), (1,0,1)]
        sage: expand_cofactors(proof, [a*b*a - a]) == a*b*a*b*a - a
        True

    A claim that does not follow from the assumptions is rejected::

        sage: F.<a,b,c> = FreeAlgebra(QQ,3)
        sage: certify([a*b + b*a + c, a*b - b*a], c*a - a*c/2, verbose=0)
        Failed! Not all ideal memberships could be verified.
        False

    TESTS:

    The cofactor representations of the Groebner basis elements have to be
    correct too::

        sage: I = NCIdeal([a*b + b*a + c, a*b - b*a])
        sage: G = I.groebner_basis(maxiter=3)
        sage: G
        [1/2*c + a*b, 1/2*c + b*a, - a*c + c*a, - b*c + c*b]
        sage: all(g.expand_cofactors(I.gens()) == g.to_native() for g in G)
        True

    The zero polynomial is a claim with an empty certificate::

        sage: certify([a*b - 1], F(0), verbose=0)
        []
    """
    
    F = assumptions[0].parent()
    X = F.gens() if not order else order
    A = MyFreeAlgebra(F.base_ring(),X)
    
    # prepare input
    original_claims_was_list = True
    if type(claims) is not list:
        claims = [A(claims)]
        original_claims_was_list = False
    else:
        claims = [A(claim) for claim in claims]  
    assumptions = [A(f) for f in assumptions]
        
    # check compatibility
    if quiver is not None:
        check_compatibility(assumptions,claims,quiver)
    
    # make ideal
    I = NCIdeal(assumptions,order=order)
    
    # main loop Groebner basis computation & reduction
    if verbose > 0:
        print("Computing a (partial) Groebner basis and reducing the claims...\n")
    idx = 0
    proved = [False] * len(claims)
    certificates = [None] * len(claims)
    
    while idx < maxiter and not all(proved):
        idx += 1
        if verbose > 0 and idx % 5 == 0:
            print("Starting iteration %d..." % idx)
        G = I.groebner_basis(maxiter=1,maxdeg=maxdeg,reset=False,verbose=verbose-1)

        #try to reduce the claim
        for i,f in enumerate(claims):
            if not proved[i]:
                h = reduced_form(G,f)
                if h.is_zero():
                    certificates[i] = h.cofactors()
                    proved[i] = True
        
    # negative outcome
    if not all(proved):
        print("Failed! Not all ideal memberships could be verified.")
        return False

    # positive outcome
    if verbose > 0:
        print("Done! Ideal membership of all claims could be verified!")
    
    # a certificate is only worth anything if it really expands to the claim
    #verify_cofactors(certificates,claims,assumptions)
    
    # check coefficients
    for certificate in certificates:
        if not all(c.c() in ZZ for c in certificate):
            warnings.warn("There appear non-integer coefficients in the cofactor representations!")

    if original_claims_was_list:
        return certificates
    else:
        return certificates[0]
############################################################################
def verify_cofactors(certificates,claims,assumptions):
    r"""
    Check that every certificate expands to the corresponding claim.

    A cofactor representation `\sum_j c_j a_j f_{i_j} b_j` is only a proof of
    the claim if it really is equal to it. Since this is cheap compared to the
    Groebner basis computation, it is verified rather than assumed.

    INPUT:

    - ``certificates`` -- a list of lists of cofactors

    - ``claims`` -- a list of NCPolynomials

    - ``assumptions`` -- a list of NCPolynomials; the generators the cofactors
      refer to

    OUTPUT: ``None``; a ``RuntimeError`` is raised if some certificate does not
    expand to the corresponding claim.
    """
    gens = [f.to_native() for f in assumptions]
    F = gens[0].parent()
    for certificate,claim in zip(certificates,claims):
        expanded = expand_cofactors(certificate,gens) if certificate else F.zero()
        if expanded != claim.to_native():
            raise RuntimeError("The computed cofactor representation of %s is not "
                               "correct. This is a bug - please report it to %s."
                               % (str(claim), "clemens.hofstadler@jku.at"))
############################################################################
def check_compatibility(assumptions,claims,Q):
    for f in assumptions:
        if not Q.is_uniformly_compatible(f):
            raise ValueError("The assumption " + f.__repr__() + " is not compatible with the quiver")
    for f in claims:
        if not Q.is_compatible(f):
                raise ValueError("The claim " + f.__repr__() + " is not compatible with the quiver")